### PR TITLE
Removed duplicates and segregated code blocks

### PR DESCRIPTION
**Pull request by TemirkhanN**
To simplify navigation and readability segregated code blocks into three main chunks. Player, tabs and launcher.  

Launcher bootstraps game engine, sessions and tabs.  
Tabs are basically pages organised as bunch of controller(which they previously were, so the only thing that changed here is that we try to reduce amount of global variables they use).  
Player is the only explicit model extracted from engine.php for now. It encapsulates player-related logic and isolates database interaction. 

Still a bunch of things to refactor but further manipulations and adjustments have to become easier from this point.

### CODE REVIEW

**Comment by crilleaz** [comment]
I like it, I think its the way moving forward. And you're right, there's a lot of left overs and just general comments to myself, there is active security issues that needs to be adressed

**Review by crilleaz — APPROVED** [review]

**Comment by TemirkhanN** [comment]
@crilleaz do you mind if we move towards using [composer](https://getcomposer.org/) ?  
It will resolve autoloading issues and allow us to use some 3rd party libraries such as database and http wrappers.

**Comment by crilleaz** [comment]
I believe the move has to be done, right now I don't have a environment that would support any higher than PHP 7.2 sadly.

**Comment by TemirkhanN** [comment]
I will perform adjustments yet will be great if at some point  you could to step in to implement/enhance features and share your vision on player interface.  

If you need any assistance with php upgrade drop me a message. php 7.4 is the lowest you should aim for since it provides really good benefits.

**Pull request merged**
